<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-9H8GI7A" failures="0" tests="5" name="testng_programs.DataProvider_FacebookSignUP" time="33.498" errors="0" timestamp="2024-05-15T19:43:00 IST" skipped="0">
  <testcase classname="testng_programs.DataProvider_FacebookSignUP" name="login_To_Facebook" time="8.130"/>
  <system-out>
    <![CDATA[Log in was attempted, not sure if it's logded in please check exception]]>
  </system-out>
  <testcase classname="testng_programs.DataProvider_FacebookSignUP" name="login_To_Facebook" time="6.405"/>
  <system-out>
    <![CDATA[Log in was attempted, not sure if it's logded in please check exception]]>
  </system-out>
  <testcase classname="testng_programs.DataProvider_FacebookSignUP" name="login_To_Facebook" time="4.975"/>
  <system-out>
    <![CDATA[Log in was attempted, not sure if it's logded in please check exception]]>
  </system-out>
  <testcase classname="testng_programs.DataProvider_FacebookSignUP" name="login_To_Facebook" time="8.554"/>
  <system-out>
    <![CDATA[Log in was attempted, not sure if it's logded in please check exception]]>
  </system-out>
  <testcase classname="testng_programs.DataProvider_FacebookSignUP" name="login_To_Facebook" time="5.434"/>
  <system-out>
    <![CDATA[Log in was attempted, not sure if it's logded in please check exception]]>
  </system-out>
</testsuite> <!-- testng_programs.DataProvider_FacebookSignUP -->
