<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-9H8GI7A" failures="0" tests="5" name="testng_programs.FacebookLogin_DataProvider" time="21.337" errors="0" timestamp="2024-05-12T18:59:25 IST" skipped="0">
  <testcase classname="testng_programs.FacebookLogin_DataProvider" name="login_To_Facebook" time="3.459"/>
  <system-out>
    <![CDATA[Log in was attempted, not sure if it's logded in please check exception]]>
  </system-out>
  <testcase classname="testng_programs.FacebookLogin_DataProvider" name="login_To_Facebook" time="3.692"/>
  <system-out>
    <![CDATA[Log in was attempted, not sure if it's logded in please check exception]]>
  </system-out>
  <testcase classname="testng_programs.FacebookLogin_DataProvider" name="login_To_Facebook" time="5.221"/>
  <system-out>
    <![CDATA[Log in was attempted, not sure if it's logded in please check exception]]>
  </system-out>
  <testcase classname="testng_programs.FacebookLogin_DataProvider" name="login_To_Facebook" time="4.476"/>
  <system-out>
    <![CDATA[Log in was attempted, not sure if it's logded in please check exception]]>
  </system-out>
  <testcase classname="testng_programs.FacebookLogin_DataProvider" name="login_To_Facebook" time="4.489"/>
  <system-out>
    <![CDATA[Log in was attempted, not sure if it's logded in please check exception]]>
  </system-out>
</testsuite> <!-- testng_programs.FacebookLogin_DataProvider -->
